name: validate-links

on: pull_request

jobs:
  validate_links_job:
    runs-on: ubuntu-latest
    name: validate-links job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
      working-directory: ./.github/actions/validate-links
    - name: validate-links action step
      uses: ./.github/actions/validate-links
